### PR TITLE
Append.only.immutable

### PR DESCRIPTION
**Pull request by lollipopman**
This pull request sets the append only flag on the files so that a user cannot truncate the files before exiting their shell.

This commit is based off of this commit by @joeripronk https://github.com/joeripronk/sudosh3/commit/d7b25e030b7f80bfcd3734d6bceb07edbd5a66ee

After the files are done being written to, we set the immutable flag so that they cannot be altered, we also chmod them to be readable by the users primary group.

I have ifdefed the necessary code so that it at least compiles on DragonflyBSD

I would love any stylistic or cross os suggestions, I have written very little C code.

### CODE REVIEW

**Comment by b1naryth1ef** [comment]
:+1:

**Comment by lollipopman** [comment]
@squash any thoughts on the patch?

**Comment by squash** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I am working to add this as a config option, off by default to avoid
breaking existing users.


On 06/22/2015 10:29 AM, lollipopman wrote:
> @squash <https://github.com/squash> any thoughts on the patch?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/squash/sudosh2/pull/7#issuecomment-114128952>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlWIHBMACgkQlrx3tV7BDaEbMwCgn+5Gg1HIeE+3R+0Mp6cI5ByC
G9gAn3BegHWF6HbRJq6Zwuqhm0cot9n0
=kNRM
-----END PGP SIGNATURE-----

**Comment by lollipopman** [comment]
> I am working to add this as a config option, off by default to avoid
breaking existing users.

Okay, I can also update the pull request with a config option, do you want it to be a command line flag?

**Comment by squash** [comment]
I would like to make it a sudosh.config option target than a compile time option. I need to validate a few platforms to be site this can be done safely.
On Jun 22, 2015 11:31 AM, lollipopman <notifications@github.com> wrote:
I am working to add this as a config option, off by default to avoid
breaking existing users.


Okay, I can also update the pull request with a config option, do you want it to be a command line flag?

**Comment by lollipopman** [comment]
@squash I updated the pull request with a config option, feedback welcome

**Comment by squash** [comment]
Some of your changes don't compile, such as:
      fprintf (stderr, "Syslog Disabled\t%s\n");

I'm cleaning them up before merging locally.

**Comment by lollipopman** [comment]
@squash good catch, thanks

**Pull request merged**
